# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户标识')),
                ('nickname', models.CharField(default='匿名用户', max_length=100, verbose_name='用户昵称')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('sex', models.CharField(default='男', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(default=123456, max_length=50, verbose_name='联系方式')),
                ('avatar', models.ImageField(default='static/users/avatar/default.jpg', upload_to='static/users/avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
