# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_auto_20181214_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品id')),
                ('name', models.CharField(max_length=50, verbose_name='商品名字')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('count', models.IntegerField(verbose_name='商品销量')),
                ('status', models.IntegerField(verbose_name='商品状态')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('desc', models.CharField(max_length=255, verbose_name='商品介绍')),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(default='static/goods/img/default.jpg', upload_to='static/goods/img/')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gt_name', models.CharField(max_length=50, verbose_name='商品类型')),
                ('gt_desc', models.CharField(default='这家伙太懒了。。。。', max_length=255, verbose_name='类型描述')),
                ('gt_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsType'),
        ),
    ]
