# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('addr', models.CharField(max_length=255)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goodsimg', models.ImageField(upload_to='static/orders/img')),
                ('goodsname', models.CharField(max_length=50)),
                ('goodsnum', models.IntegerField()),
                ('goodsprice', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
            ],
        ),
    ]
